// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"
)

type User struct {
	ID         int32     `json:"id"`
	Username   string    `json:"username"`
	CreatedAt  time.Time `json:"created_at"`
	Passwdhash string    `json:"passwdhash"`
	Email      string    `json:"email"`
}
